{
 "title": "CFEngine Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Promises",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (cfengine_promises_kept{job=\"cfengine-exporter\"} + cfengine_promises_notkept{job=\"cfengine-exporter\"} + cfengine_promises_repaired{job=\"cfengine-exporter\"}) without (ip)"
    }
   ]
  },
  {
   "title": "Promise Status Overivew",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (cfengine_promises_kept{job=\"cfengine-exporter\"}) without (ip)",
     "legendFormat": "Kept"
    },
    {
     "expr": "sum (cfengine_promises_repaired{job=\"cfengine-exporter\"}) without (ip)",
     "legendFormat": "Repaired"
    },
    {
     "expr": "sum (cfengine_promises_notkept{job=\"cfengine-exporter\"}) without (ip)",
     "legendFormat": "Not Kept"
    }
   ]
  },
  {
   "title": "Last Seen",
   "type": "table",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(time() - cfengine_lastseen_timestamp) by (ip)"
    }
   ]
  },
  {
   "title": "Changes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(cfengine_changes_notkept_total{job=\"cfengine-exporter\"}[1m])) by (job, namespace) + sum(irate(cfengine_changes_repaired_total{job=\"cfengine-exporter\"}[1m])) by (job, namespace)",
     "legendFormat": "Changes"
    }
   ]
  }
 ]
}